apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default 
  name: kdaudit 
  labels:
    app: kdaudit 
    component: kdaudit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kdaudit
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kdaudit
subjects:
- kind: ServiceAccount
  name: kdaudit
  namespace: default 
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: kdaudit
